"""
Templates for generated project artifacts.
Includes Dockerfiles, run scripts, READMEs, and safety markers.
"""

# =============================================================================
# DOCKERFILE TEMPLATES
# =============================================================================

PYTHON_DOCKERFILE = '''# Auto-generated Dockerfile for {project_name}
# ⚠️  MVP ONLY - Not for production use

FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Create directories
RUN mkdir -p data results

# Expose port
ENV PORT=${{PORT:-5000}}

# Health check - uses PORT env var set at runtime via docker run -e PORT=X
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD python -c "import urllib.request,os;urllib.request.urlopen(f'http://127.0.0.1:{{}}'.format(os.environ.get('PORT','5000'))+'/health',timeout=3)" || exit 1

# Run
CMD ["python", "app.py"]
'''

NODEJS_DOCKERFILE = '''# Auto-generated Dockerfile for {project_name}
# ⚠️  MVP ONLY - Not for production use

FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy application
COPY . .

# Create directories
RUN mkdir -p data results

# Expose port
EXPOSE ${{PORT:-5000}}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${{PORT:-5000}}/health || exit 1

# Run
CMD ["node", "app.js"]
'''


# =============================================================================
# DOCKER COMPOSE
# =============================================================================

DOCKER_COMPOSE = '''# Docker Compose for {project_name}
# Run with: docker-compose up

version: '3.8'

services:
  app:
    build: .
    ports:
      - "${{PORT:-5000}}:${{PORT:-5000}}"
    environment:
      - PORT=${{PORT:-5000}}
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    restart: unless-stopped
'''


# =============================================================================
# RUN SCRIPTS
# =============================================================================

PYTHON_RUN_SCRIPT_WIN = '''@echo off
REM Run script for {project_name}
echo Starting {project_name}...

REM Check Python
python --version >nul 2>&1 || (echo Python not found && exit /b 1)

REM Install deps if needed
if exist requirements.txt pip install -r requirements.txt -q

REM Create directories
if not exist data mkdir data
if not exist results mkdir results

REM Run
python app.py
'''

PYTHON_RUN_SCRIPT_UNIX = '''#!/bin/bash
# Run script for {project_name}
echo "Starting {project_name}..."

# Check Python
command -v python3 >/dev/null 2>&1 || {{ echo "Python3 required"; exit 1; }}

# Install deps
[ -f requirements.txt ] && pip install -r requirements.txt -q

# Create directories
mkdir -p data results

# Run
python3 app.py
'''

NODEJS_RUN_SCRIPT_WIN = '''@echo off
REM Run script for {project_name}
echo Starting {project_name}...

REM Check Node
node --version >nul 2>&1 || (echo Node.js not found && exit /b 1)

REM Install deps
if exist package.json npm install --silent

REM Create directories
if not exist data mkdir data
if not exist results mkdir results

REM Run
node app.js
'''

NODEJS_RUN_SCRIPT_UNIX = '''#!/bin/bash
# Run script for {project_name}
echo "Starting {project_name}..."

# Check Node
command -v node >/dev/null 2>&1 || {{ echo "Node.js required"; exit 1; }}

# Install deps
[ -f package.json ] && npm install --silent

# Create directories
mkdir -p data results

# Run
node app.js
'''


# =============================================================================
# README TEMPLATE
# =============================================================================

README_TEMPLATE = '''# {project_name}

> ⚠️ **MVP / PROTOTYPE** - Auto-generated by PaperForge AI
> This is a demonstration implementation, NOT production-ready code.

## Overview

{summary}

**Algorithm:** {algorithm_name}

## Quick Start

### Option 1: Direct Run
```bash
# Python
pip install -r requirements.txt
python app.py

# Node.js
npm install
node app.js
```

### Option 2: Docker
```bash
docker-compose up
```

Then open: **http://localhost:{port}**

## API Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| GET | `/` | Landing page with test form |
| GET | `/health` | Health check |
| GET | `/info` | Algorithm information |
| POST | `/run` | Execute algorithm |
| GET | `/results` | List previous results |

## Example Usage

```bash
curl -X POST http://localhost:{port}/run \\
  -H "Content-Type: application/json" \\
  -d '{{"data": [1, 2, 3, 4, 5]}}'
```

## Project Structure

```
{project_name}/
├── app.{ext}           # API server
├── algorithm.{ext}     # Core algorithm
├── requirements.txt    # Dependencies (Python)
├── package.json        # Dependencies (Node.js)
├── Dockerfile          # Container config
├── docker-compose.yml  # Docker orchestration
├── run.bat / run.sh    # Run scripts
├── data/               # Input data
└── results/            # Output results
```

## Limitations

⚠️ This is an MVP implementation:
- Single-user only
- No authentication
- In-memory/JSON storage only
- Not optimized for performance
- May contain simplifications from original paper

## Generated By

[PaperForge AI](https://github.com/your-repo/PaperForge AI) - Research Paper to MVP Generator

---
*Auto-generated on {timestamp}*
'''


# =============================================================================
# ENV TEMPLATE
# =============================================================================

ENV_TEMPLATE = '''# Environment variables for {project_name}
# Copy to .env and customize

# Server port
PORT=5000

# Logging level (DEBUG, INFO, WARNING, ERROR)
LOG_LEVEL=INFO
'''


# =============================================================================
# DEPLOYMENT CONFIGS (Railway, Fly.io, Render)
# =============================================================================

RAILWAY_CONFIG = '''# railway.json - Railway deployment config
# Deploy with: railway up

{{
  "build": {{
    "builder": "DOCKERFILE"
  }},
  "deploy": {{
    "startCommand": "{start_command}",
    "healthcheckPath": "/health",
    "healthcheckTimeout": 100
  }}
}}
'''

FLYIO_CONFIG = '''# fly.toml - Fly.io deployment config
# Deploy with: fly deploy

app = "{app_name}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = {port}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[checks]
  [checks.health]
    type = "http"
    port = {port}
    path = "/health"
    interval = "30s"
    timeout = "5s"
'''

RENDER_CONFIG = '''# render.yaml - Render deployment config
# Connect your GitHub repo to Render and it will auto-deploy

services:
  - type: web
    name: {app_name}
    env: {env_type}
    buildCommand: "{build_command}"
    startCommand: "{start_command}"
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: {port}
'''

PROCFILE_TEMPLATE = '''# Procfile for Heroku/Railway deployment
web: {start_command}
'''


# =============================================================================
# JSON STORAGE TEMPLATE
# =============================================================================

PYTHON_JSON_STORAGE = '''"""
JSON File Storage Module
Simple CRUD operations using JSON files for persistence.
"""
import json
from pathlib import Path
from typing import Optional, Any
from datetime import datetime


class JSONStorage:
    """JSON file-based storage for MVP persistence."""

    def __init__(self, data_dir: str = "data"):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def _get_file(self, collection: str) -> Path:
        return self.data_dir / f"{{collection}}.json"

    def _load(self, collection: str) -> list[dict]:
        file = self._get_file(collection)
        if not file.exists():
            return []
        try:
            return json.loads(file.read_text())
        except:
            return []

    def _save(self, collection: str, data: list[dict]):
        file = self._get_file(collection)
        file.write_text(json.dumps(data, indent=2, default=str))

    def create(self, collection: str, item: dict) -> dict:
        """Create a new item in the collection."""
        data = self._load(collection)
        item['id'] = str(len(data) + 1)
        item['created_at'] = datetime.now().isoformat()
        data.append(item)
        self._save(collection, data)
        return item

    def read(self, collection: str, item_id: str) -> Optional[dict]:
        """Read a single item by ID."""
        data = self._load(collection)
        return next((x for x in data if str(x.get('id')) == str(item_id)), None)

    def read_all(self, collection: str) -> list[dict]:
        """Read all items in a collection."""
        return self._load(collection)

    def update(self, collection: str, item_id: str, updates: dict) -> Optional[dict]:
        """Update an existing item."""
        data = self._load(collection)
        for i, item in enumerate(data):
            if str(item.get('id')) == str(item_id):
                data[i] = {{**item, **updates, 'updated_at': datetime.now().isoformat()}}
                self._save(collection, data)
                return data[i]
        return None

    def delete(self, collection: str, item_id: str) -> bool:
        """Delete an item by ID."""
        data = self._load(collection)
        original_len = len(data)
        data = [x for x in data if str(x.get('id')) != str(item_id)]
        if len(data) < original_len:
            self._save(collection, data)
            return True
        return False


# Singleton instance
storage = JSONStorage()
'''

NODEJS_JSON_STORAGE = '''/**
 * JSON File Storage Module
 * Simple CRUD operations using JSON files for persistence.
 */
const fs = require('fs');
const path = require('path');

class JSONStorage {{
  constructor(dataDir = 'data') {{
    this.dataDir = dataDir;
    if (!fs.existsSync(dataDir)) {{
      fs.mkdirSync(dataDir, {{ recursive: true }});
    }}
  }}

  _getFile(collection) {{
    return path.join(this.dataDir, `${{collection}}.json`);
  }}

  _load(collection) {{
    const file = this._getFile(collection);
    if (!fs.existsSync(file)) return [];
    try {{
      return JSON.parse(fs.readFileSync(file, 'utf8'));
    }} catch {{
      return [];
    }}
  }}

  _save(collection, data) {{
    const file = this._getFile(collection);
    fs.writeFileSync(file, JSON.stringify(data, null, 2));
  }}

  create(collection, item) {{
    const data = this._load(collection);
    item.id = String(data.length + 1);
    item.created_at = new Date().toISOString();
    data.push(item);
    this._save(collection, data);
    return item;
  }}

  read(collection, itemId) {{
    const data = this._load(collection);
    return data.find(x => String(x.id) === String(itemId)) || null;
  }}

  readAll(collection) {{
    return this._load(collection);
  }}

  update(collection, itemId, updates) {{
    const data = this._load(collection);
    const index = data.findIndex(x => String(x.id) === String(itemId));
    if (index === -1) return null;
    data[index] = {{ ...data[index], ...updates, updated_at: new Date().toISOString() }};
    this._save(collection, data);
    return data[index];
  }}

  delete(collection, itemId) {{
    const data = this._load(collection);
    const filtered = data.filter(x => String(x.id) !== String(itemId));
    if (filtered.length < data.length) {{
      this._save(collection, filtered);
      return true;
    }}
    return false;
  }}
}}

module.exports = new JSONStorage();
'''


# =============================================================================
# SAFETY BANNER (injected into generated code)
# =============================================================================

PYTHON_SAFETY_BANNER = '''"""
╔═══════════════════════════════════════════════════════════════════╗
║  ⚠️  AUTO-GENERATED MVP - NOT FOR PRODUCTION USE                  ║
║                                                                    ║
║  This code was automatically generated by PaperForge AI from a       ║
║  research paper. It is intended for demonstration purposes only.  ║
║                                                                    ║
║  Limitations:                                                      ║
║  - No authentication or authorization                             ║
║  - No input validation beyond basic type checks                   ║
║  - In-memory/JSON storage only                                    ║
║  - Not tested for edge cases                                      ║
║  - May not fully match paper's algorithm                          ║
╚═══════════════════════════════════════════════════════════════════╝
"""
'''

NODEJS_SAFETY_BANNER = '''/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  ⚠️  AUTO-GENERATED MVP - NOT FOR PRODUCTION USE                  ║
 * ║                                                                    ║
 * ║  This code was automatically generated by PaperForge AI from a       ║
 * ║  research paper. It is intended for demonstration purposes only.  ║
 * ║                                                                    ║
 * ║  Limitations:                                                      ║
 * ║  - No authentication or authorization                             ║
 * ║  - No input validation beyond basic type checks                   ║
 * ║  - In-memory/JSON storage only                                    ║
 * ║  - Not tested for edge cases                                      ║
 * ║  - May not fully match paper's algorithm                          ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 */
'''


def generate_project_artifacts(
    project_dir,
    project_name: str,
    language: str,
    algorithm_name: str,
    summary: str,
    port: int = 5000
) -> None:
    """
    Generate all supporting artifacts for a project.
    """
    from pathlib import Path
    from datetime import datetime

    project_dir = Path(project_dir)
    ext = "py" if language == "python" else "js"

    # Create directories
    (project_dir / "data").mkdir(exist_ok=True)
    (project_dir / "results").mkdir(exist_ok=True)

    # Dockerfile
    dockerfile = PYTHON_DOCKERFILE if language == "python" else NODEJS_DOCKERFILE
    (project_dir / "Dockerfile").write_text(
        dockerfile.format(project_name=project_name),
        encoding="utf-8"
    )

    # Docker Compose
    (project_dir / "docker-compose.yml").write_text(
        DOCKER_COMPOSE.format(project_name=project_name),
        encoding="utf-8"
    )

    # Run scripts
    if language == "python":
        (project_dir / "run.bat").write_text(
            PYTHON_RUN_SCRIPT_WIN.format(project_name=project_name),
            encoding="utf-8"
        )
        (project_dir / "run.sh").write_text(
            PYTHON_RUN_SCRIPT_UNIX.format(project_name=project_name),
            encoding="utf-8"
        )
    else:
        (project_dir / "run.bat").write_text(
            NODEJS_RUN_SCRIPT_WIN.format(project_name=project_name),
            encoding="utf-8"
        )
        (project_dir / "run.sh").write_text(
            NODEJS_RUN_SCRIPT_UNIX.format(project_name=project_name),
            encoding="utf-8"
        )

    # README
    (project_dir / "README.md").write_text(
        README_TEMPLATE.format(
            project_name=project_name,
            summary=summary,
            algorithm_name=algorithm_name,
            port=port,
            ext=ext,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M")
        ),
        encoding="utf-8"
    )

    # .env template
    (project_dir / ".env.example").write_text(
        ENV_TEMPLATE.format(project_name=project_name),
        encoding="utf-8"
    )

    # .gitignore for generated project
    (project_dir / ".gitignore").write_text(
        """# Generated project gitignore
node_modules/
__pycache__/
*.pyc
.env
results/*.json
data/*.json
*.log
""",
        encoding="utf-8"
    )

    # .dockerignore - prevents bloated Docker builds
    (project_dir / ".dockerignore").write_text(
        """node_modules/
__pycache__/
*.pyc
.env
.git/
.gitignore
*.bak
*.log
*.md
docker-compose.yml
fly.toml
railway.json
render.yaml
Procfile
run.bat
run.sh
.env.example
.dockerignore
""",
        encoding="utf-8"
    )


def inject_safety_banner(code: str, language: str) -> str:
    """Inject safety banner at the top of generated code."""
    banner = PYTHON_SAFETY_BANNER if language == "python" else NODEJS_SAFETY_BANNER
    return banner + "\n" + code


def generate_deployment_configs(
    project_dir,
    project_name: str,
    language: str,
    port: int = 5000
) -> None:
    """
    Generate deployment configuration files for various platforms.
    Supports Railway, Fly.io, Render, and Heroku.
    """
    from pathlib import Path

    project_dir = Path(project_dir)

    # Determine start command
    if language == "python":
        start_command = "python app.py"
        build_command = "pip install -r requirements.txt"
        env_type = "python"
    else:
        start_command = "node app.js"
        build_command = "npm install"
        env_type = "node"

    # App name (sanitized)
    import re
    app_name = re.sub(r'[^a-z0-9-]', '-', project_name.lower())[:30]

    # Railway config
    (project_dir / "railway.json").write_text(
        RAILWAY_CONFIG.format(start_command=start_command),
        encoding="utf-8"
    )

    # Fly.io config
    (project_dir / "fly.toml").write_text(
        FLYIO_CONFIG.format(app_name=app_name, port=port),
        encoding="utf-8"
    )

    # Render config
    (project_dir / "render.yaml").write_text(
        RENDER_CONFIG.format(
            app_name=app_name,
            env_type=env_type,
            build_command=build_command,
            start_command=start_command,
            port=port
        ),
        encoding="utf-8"
    )

    # Procfile (Heroku/Railway)
    (project_dir / "Procfile").write_text(
        PROCFILE_TEMPLATE.format(start_command=start_command),
        encoding="utf-8"
    )


def generate_json_storage(project_dir, language: str) -> None:
    """Generate JSON storage module for the project."""
    from pathlib import Path

    project_dir = Path(project_dir)

    if language == "python":
        (project_dir / "json_storage.py").write_text(
            PYTHON_JSON_STORAGE,
            encoding="utf-8"
        )
    else:
        (project_dir / "jsonStorage.js").write_text(
            NODEJS_JSON_STORAGE,
            encoding="utf-8"
        )
